# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20170801_1228_squashed_0037_auto_20190222_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='dist_desc',
            field=models.TextField(blank=True, help_text='Detailed text description of what the online resource is/does', null=True, verbose_name='Distribution description'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='externalDataReference',
            field=models.TextField(blank=True, help_text='Add an External Data Reference', null=True, verbose_name='External Data Reference'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='inspireA_I',
            field=models.TextField(blank=True, help_text='Select inspire category annex i to change', null=True, verbose_name='Inspire category Annex I'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='inspireA_II',
            field=models.TextField(blank=True, help_text='Select inspire category annex ii to change', null=True, verbose_name='Inspire category Annex II'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='inspireA_III',
            field=models.TextField(blank=True, help_text='Select inspire category annex iii to change', null=True, verbose_name='Inspire category Annex III'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='paRefId',
            field=models.TextField(blank=True, help_text='Add a Protected Area Reference WDPAID code', null=True, verbose_name='Add a Protected Area Reference (wdpaid)'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='sugg_cit',
            field=models.TextField(blank=True, help_text="General explanation of the data producer's knowledge about the lineage of a dataset", null=True, verbose_name='Suggested citation'),
        ),
    ]
